### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by burgalon** [motiz88/react-dygraphs#3]

**Comment by burgalon** [comment]
Can you please publish to NPM? Right now without publishing, the npm build script is not triggered

**Comment by motiz88** [comment]
Hey, sorry it took this long.
https://www.npmjs.com/package/react-dygraphs

**Comment by burgalon** [comment]
It seems like the package still doesn't contain the dist directory

**Comment by motiz88** [comment]
I don't quite follow you, but I want to help. Please bear with me as we go through the details.

* AFAICT the package I published to npm, at version 0.0.1, is OK and does contain a `dist` folder. (Are you doing `npm install react-dygraphs` or something else?)
* My `package.json` does contain a `prepublish` script, [here](https://github.com/motiz88/react-dygraphs/blob/master/package.json#L11).
* The git repo does not and will not track the files in `dist`, as it is not meant to be depended upon directly. (And `git clone ... && cd react-dygraphs && npm install` does correctly trigger a build)

Where are you having a problem?

**Comment by burgalon** [comment]
my mistake on the npm package.
