### ISSUE TITLE
demo/index.jsx references util

### ISSUE THREAD

**Issue by dmr** [motiz88/react-dygraphs#6]
I cannot find that file in git. Can it be removed?

**Comment by motiz88** [comment]
That's [util from Node.js](https://nodejs.org/api/util.html), or rather, from [node-libs-browser](https://github.com/webpack/node-libs-browser) in this case.

The demo is meant to run using `webpack-dev-server` and [the supplied webpack config](https://github.com/motiz88/react-dygraphs/blob/master/webpack.config.js) - a setup in which `util` is available.

Anyway, you'll notice that the demo page only needs `util` for `util.inspect`. I don't know what you're trying to achieve exactly (or how), but I'm guessing you can probably change that line to do suit your needs and remove the reference to `util` entirely.
