### ISSUE TITLE
Date labels

### ISSUE THREAD

**Issue by MaffooBristol** [motiz88/react-dygraphs#8]
Hi, this may be something I've just completely missed, but I noticed that whilst Dygraphs should natively and automatically parse dates on the X-axis, react-dygraphs doesn't seem to do this. Is this a known bug or am I doing it wrong?

When I run the following example code, nothing shows up on the X-axis and no line is drawn, but replacing the dates with an index works fine. Any thoughts? Thanks in advance!

```javascript
import React from 'react';
import Dygraph from 'react-dygraphs';

export default class Chart extends React.Component {
  render () {
    const labels = ['Date', 'Amount'];
    const graphData = [['2015-01-01',10], ['2015-01-02', 20], ['2015-01-04', 14]];
    return <Dygraph data={graphData} labels={labels} height={600} width={1200} />;
  }
}
```

**Comment by motiz88** [comment]
Hi Matt, thanks for the report. I looked at http://dygraphs.com/data.html#array and it seems to indicate that strings aren't parsed when passing an array (as opposed to CSV data etc), so you should construct and pass `Date` objects rather than date strings. If this doesn't work for you I'd love to keep looking into it.

**Comment by motiz88** [comment]
Also, here is the propTypes definition that applies to `data` (and reflects the Dygraphs docs as far as I can tell):
https://github.com/motiz88/react-dygraphs/blob/master/src/components/Dygraph/options.js#L40

**Comment by MaffooBristol** [comment]
Ahh, thanks for getting back to me Moti! That makes sense- I haven't really delved too deeply into Dygraph's documentation, but has just assumed that the object parsing would work the same as CSV, bit strange that it doesn't tbh, but clearly not the fault of your module!

Just gave it a go with a date object, and it now works with:
```javascript
return [new Date(Moment(row.Date, 'DD/MM/YYYY')), row.Value];
```

Thanks!
